"""Repeat-unit stereochemistry inspection and tacticity sequence generation."""

import math
import random
from dataclasses import dataclass
from typing import Literal

from rdkit import Chem

from island.chemistry.psmiles import RepeatUnit
from island.exceptions import (
    TacticityError,
    UnsupportedStereochemistryError,
)

Tacticity = Literal["isotactic", "syndiotactic", "atactic"]
StereoState = Literal["R", "S"]


@dataclass(frozen=True)
class StereocenterInfo:
    """A tetrahedral stereocenter perceived in a repeat-unit graph."""

    atom_index: int
    cip_label: str | None
    assigned: bool
    backbone_relevant: bool
    chiral_tag: str


@dataclass(frozen=True)
class RepeatUnitStereochemistry:
    """Stereochemical inspection result for one repeat unit."""

    centers: tuple[StereocenterInfo, ...]
    backbone_path: tuple[int, ...]

    @property
    def relevant_centers(self) -> tuple[StereocenterInfo, ...]:
        return tuple(center for center in self.centers if center.backbone_relevant)

    @property
    def controllable_center(self) -> StereocenterInfo | None:
        relevant = self.relevant_centers
        if len(relevant) == 1 and relevant[0].assigned:
            return relevant[0]
        return None


@dataclass(frozen=True)
class StereochemicalSequence:
    """Ordered absolute states generated from a repeat-unit reference state.

    The reference state is the CIP state encoded by the input PSMILES. Its
    opposite is generated by graph-level tetrahedral-tag inversion.
    """

    states: tuple[StereoState, ...]
    tacticity: Tacticity
    reference_state: StereoState
    stereo_seed: int | None = None
    inverted_fraction: float | None = None

    @property
    def number_of_repeat_units(self) -> int:
        return len(self.states)


def inspect_repeat_unit_stereochemistry(
    repeat_unit: RepeatUnit,
) -> RepeatUnitStereochemistry:
    """Inspect real tetrahedral centers on the head-to-tail backbone path."""
    mol = Chem.Mol(repeat_unit.mol)
    Chem.AssignStereochemistry(mol, cleanIt=True, force=True)
    backbone_path = tuple(
        Chem.GetShortestPath(
            mol,
            repeat_unit.head.neighbor_atom_index,
            repeat_unit.tail.neighbor_atom_index,
        )
    )
    perceived = Chem.FindMolChiralCenters(
        mol,
        includeUnassigned=True,
        includeCIP=True,
        useLegacyImplementation=False,
    )
    centers = tuple(
        StereocenterInfo(
            atom_index=atom_index,
            cip_label=label if label in {"R", "S"} else None,
            assigned=label in {"R", "S"},
            backbone_relevant=atom_index in backbone_path
            and mol.GetAtomWithIdx(atom_index).GetAtomicNum() != 0,
            chiral_tag=str(mol.GetAtomWithIdx(atom_index).GetChiralTag()),
        )
        for atom_index, label in perceived
        if mol.GetAtomWithIdx(atom_index).GetAtomicNum() != 0
    )
    return RepeatUnitStereochemistry(centers, backbone_path)


def require_controllable_stereocenter(repeat_unit: RepeatUnit) -> StereocenterInfo:
    """Return the single assigned backbone center or raise a precise error."""
    inspection = inspect_repeat_unit_stereochemistry(repeat_unit)
    relevant = inspection.relevant_centers
    if not relevant:
        raise UnsupportedStereochemistryError(
            "Tacticity requires one backbone-relevant tetrahedral stereocenter; "
            "this repeat unit has none"
        )
    if len(relevant) > 1:
        raise UnsupportedStereochemistryError(
            "Phase 3.6A supports exactly one backbone-relevant tetrahedral "
            f"stereocenter per repeat unit; found {len(relevant)}"
        )
    center = relevant[0]
    if not center.assigned:
        raise UnsupportedStereochemistryError(
            "The backbone-relevant stereocenter is unassigned; encode an explicit "
            "@ or @@ configuration in the repeat-unit PSMILES"
        )
    return center


def invert_repeat_unit_stereochemistry(
    repeat_unit: RepeatUnit,
) -> RepeatUnit:
    """Return the graph enantiomer at the one controllable repeat-unit center."""
    center = require_controllable_stereocenter(repeat_unit)
    mol = Chem.Mol(repeat_unit.mol)
    atom = mol.GetAtomWithIdx(center.atom_index)
    tag = atom.GetChiralTag()
    if tag == Chem.ChiralType.CHI_TETRAHEDRAL_CW:
        atom.SetChiralTag(Chem.ChiralType.CHI_TETRAHEDRAL_CCW)
    elif tag == Chem.ChiralType.CHI_TETRAHEDRAL_CCW:
        atom.SetChiralTag(Chem.ChiralType.CHI_TETRAHEDRAL_CW)
    else:
        raise UnsupportedStereochemistryError(
            "The controllable center does not use supported tetrahedral chirality"
        )
    Chem.AssignStereochemistry(mol, cleanIt=True, force=True)
    inverted_label = (
        mol.GetAtomWithIdx(center.atom_index).GetProp("_CIPCode")
        if mol.GetAtomWithIdx(center.atom_index).HasProp("_CIPCode")
        else None
    )
    if inverted_label not in {"R", "S"} or inverted_label == center.cip_label:
        raise UnsupportedStereochemistryError(
            "RDKit could not produce the opposite repeat-unit stereochemistry"
        )
    return RepeatUnit(
        original_psmiles=repeat_unit.original_psmiles,
        mol=mol,
        head=repeat_unit.head,
        tail=repeat_unit.tail,
    )


def generate_stereochemical_sequence(
    number_of_repeat_units: int,
    tacticity: Tacticity,
    *,
    reference_state: StereoState,
    stereo_seed: int = 2026,
    atactic_fraction: float = 0.5,
) -> StereochemicalSequence:
    """Generate R/S states independently of chemistry and coordinates.

    ``atactic_fraction`` is the target fraction of states inverted relative to
    ``reference_state``. The nearest integer count is shuffled by a local RNG.
    """
    if (
        not isinstance(number_of_repeat_units, int)
        or isinstance(number_of_repeat_units, bool)
        or number_of_repeat_units < 1
    ):
        raise TacticityError("Stereochemical sequence length must be an integer >= 1")
    if tacticity not in {"isotactic", "syndiotactic", "atactic"}:
        raise TacticityError(
            "tacticity must be 'isotactic', 'syndiotactic', or 'atactic'"
        )
    if reference_state not in {"R", "S"}:
        raise TacticityError("reference_state must be 'R' or 'S'")
    if not isinstance(stereo_seed, int) or isinstance(stereo_seed, bool):
        raise TacticityError("stereo_seed must be an integer")
    opposite: StereoState = "S" if reference_state == "R" else "R"
    if tacticity == "isotactic":
        states = (reference_state,) * number_of_repeat_units
        return StereochemicalSequence(states, tacticity, reference_state)
    if tacticity == "syndiotactic":
        states = tuple(
            reference_state if index % 2 == 0 else opposite
            for index in range(number_of_repeat_units)
        )
        return StereochemicalSequence(states, tacticity, reference_state)
    if (
        not isinstance(atactic_fraction, (int, float))
        or isinstance(atactic_fraction, bool)
        or not 0.0 <= float(atactic_fraction) <= 1.0
    ):
        raise TacticityError("atactic_fraction must be between 0 and 1")
    inverted_count = math.floor(number_of_repeat_units * atactic_fraction + 0.5)
    states_list: list[StereoState] = [opposite] * inverted_count + [reference_state] * (
        number_of_repeat_units - inverted_count
    )
    random.Random(stereo_seed).shuffle(states_list)
    return StereochemicalSequence(
        tuple(states_list),
        tacticity,
        reference_state,
        stereo_seed=stereo_seed,
        inverted_fraction=float(atactic_fraction),
    )
